# Generated by Django 4.1.7 on 2023-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('CA', 'Capsules'), ('DR', 'Drops'), ('PO', 'Powder'), ('LI', 'Liquid'), ('TA', 'Tablets'), ('OT', 'Other')], default='OT', max_length=50),
        ),
    ]
