# Generated by Django 4.1.7 on 2023-03-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='client_id',
            new_name='client',
        ),
    ]
