# Generated by Django 4.1.7 on 2023-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('PHARMACIST', 'Pharmacist')], default='ADMIN', max_length=50),
        ),
    ]
