# Generated by Django 4.1.7 on 2023-03-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_remove_user_cnp_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='user',
            name='cnp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
