# Generated by Django 4.1.7 on 2023-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_clientprofile_user_delete_client_user_cnp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('PHARMACIST', 'Pharmacist')], default='CLIENT', max_length=50),
        ),
    ]
